[server]
headless = true
port = 3000
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false

[browser]
serverAddress = "localhost"
serverPort = 3000
gatherUsageStats = false
